Add fix for redirect middleware for #276
http-rs/surf pull request #279
Opened 2021-01-31 06:20 UTC by hipstermojo

This fix will require a clone of the original base URL which can then be joined to the value in the `LOCATION` header if it is a relative path. Previously this would simply return an Error for RelativeURLWithoutBase.

An example of such a URL is https://blog.thomasheartman.com/posts/on-generics-and-associated-types which would redirect to add a trailing slash.

2021-02-11 23:52 UTC, Fishrock123 requested changes

2021-02-11 23:52 UTC, Fishrock123 commented on src/middleware/redirect/mod.rs
> +                        Ok(valid_url) => valid_url,
This is not quite complete, a redirect could give us a full url and then a future one could give us a partial one.

I think this branch should also update the`base_url`.

2021-02-12 03:35 UTC, hipstermojo commented
The linting issues with Clippy are technically outside the scope of this PR so I'm not sure if I should edit that part or not.

2021-02-12 19:50 UTC, Fishrock123 approved these changes
Could you rebase so that CI updates? thanks, looks good otherwise.

2021-03-01 23:10 UTC, Fishrock123 commented
Merged the exact same commits in https://github.com/http-rs/surf/pull/293 - for some reason there was still a rebase issue here.

Thanks!!

2021-03-01 23:10 UTC, closed without merging